hapi:
  fhir:
    datasource:
      url: jdbc:postgresql://fhir-db:5432/fhir
      username: fhiruser
      password: fhirpassword
    security:
      oAuth2:
        enable: true
        clientId: fhir-server-client
        clientSecret: YOUR_CLIENT_SECRET
        issuer: http://localhost:8080/realms/your-realm
        tokenUrl: http://localhost:8080/realms/your-realm/protocol/openid-connect/token
        introspectionUrl: http://localhost:8080/realms/your-realm/protocol/openid-connect/token/introspect
        jwksUrl: http://localhost:8080/realms/your-realm/protocol/openid-connect/certs

spring:
  datasource:
    url: jdbc:postgresql://fhir-db:5432/fhir
    username: fhiruser
    password: fhirpassword
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    ca.uhn.fhir.jpa: DEBUG

