services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: medical_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./medical_db.sql:/docker-entrypoint-initdb.d/medical_db.sql:Z

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak-config/realm-export.json:/opt/keycloak/data/import/realm-export.json:Z
    command: ["start-dev", "--import-realm"]

volumes:
  postgres_data: