services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-config/realm-export.json:/opt/keycloak/data/import/realm-export.json:Z
    command: ["start-dev", "--import-realm"]

  hapi-fhir:
    image: hapiproject/hapi:latest # Image du serveur HAPI FHIR
    container_name: hapi-fhir
    ports:
      - 8081:8080
    environment:
      HAPI_FHIR_VERSION: r4 # Version du standard FHIR
    volumes:
      - hapi_data:/var/lib/jetty/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/fhir"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  keycloak_data:
  hapi_data:
