services:
  keycloak1:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-config/realm-export.json:/opt/keycloak/data/import/realm-export.json:Z
    command: ["start-dev", "--import-realm"]

  hapi-fhir1:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir
    ports:
      - 8081:8080
    environment:
      HAPI_FHIR_VERSION: r4
    volumes:
      - hapi_data:/var/lib/jetty/data


volumes:
  keycloak_data:
  hapi_data: